apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  selector:
    matchLabels:
       app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: user
        image: rajsingh6/orderservice:v2
        ports:
          - containerPort: 8060
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "dev"
---
apiVersion: v1
kind: Service
metadata:
    name: order-service
spec:
    type: ClusterIP
    selector:
        app: order
    ports:
    - port: 8060
      targetPort: 8060
        